version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Tests
          command: bundle exec rspec -f d 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
